-- Academic tables: students, guardians, classes, sections, subjects, admission_applications, timetable_slots, curriculum

-- Sections (branch-level)
CREATE TABLE sections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_sections_branch ON sections(branch_id);

-- Classes
CREATE TABLE classes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  grade TEXT,
  section_id UUID REFERENCES sections(id) ON DELETE SET NULL,
  capacity INTEGER,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_classes_branch ON classes(branch_id);
CREATE INDEX idx_classes_section ON classes(section_id);

-- Subjects
CREATE TABLE subjects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_subjects_branch ON subjects(branch_id);

-- Guardians
CREATE TYPE guardian_relation AS ENUM ('father', 'mother', 'guardian', 'other');

CREATE TABLE guardians (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  relation guardian_relation DEFAULT 'guardian',
  auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_guardians_school ON guardians(school_id);
CREATE INDEX idx_guardians_email ON guardians(email);

-- Students (student_id generated by trigger in 00006)
CREATE TYPE student_status AS ENUM ('active', 'graduated', 'inactive');

CREATE TABLE students (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  student_id TEXT UNIQUE,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  date_of_birth DATE NOT NULL,
  gender TEXT,
  class_id UUID REFERENCES classes(id) ON DELETE SET NULL,
  status student_status DEFAULT 'active',
  auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_students_school ON students(school_id);
CREATE INDEX idx_students_branch ON students(branch_id);
CREATE INDEX idx_students_class ON students(class_id);
CREATE INDEX idx_students_student_id ON students(student_id);

-- Guardian-Student many-to-many
CREATE TABLE guardian_students (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  guardian_id UUID NOT NULL REFERENCES guardians(id) ON DELETE CASCADE,
  student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(guardian_id, student_id)
);

CREATE INDEX idx_guardian_students_guardian ON guardian_students(guardian_id);
CREATE INDEX idx_guardian_students_student ON guardian_students(student_id);

-- Admission applications
CREATE TYPE admission_source AS ENUM ('online', 'manual');
CREATE TYPE admission_status AS ENUM ('pending', 'approved', 'rejected');

CREATE TABLE admission_applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  student_name TEXT NOT NULL,
  dob DATE,
  gender TEXT,
  class_applying TEXT,
  guardian_name TEXT NOT NULL,
  guardian_email TEXT NOT NULL,
  guardian_phone TEXT,
  relation guardian_relation DEFAULT 'guardian',
  source admission_source DEFAULT 'manual',
  status admission_status DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_admission_applications_school ON admission_applications(school_id);
CREATE INDEX idx_admission_applications_status ON admission_applications(status);

-- Timetable slots (teacher_id references profiles)
CREATE TABLE timetable_slots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  class_id UUID NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  day INTEGER NOT NULL CHECK (day >= 0 AND day <= 6),
  period INTEGER NOT NULL,
  subject_id UUID REFERENCES subjects(id) ON DELETE SET NULL,
  teacher_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(class_id, day, period)
);

CREATE INDEX idx_timetable_slots_class ON timetable_slots(class_id);

-- Curriculum
CREATE TABLE curriculum (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  grade TEXT NOT NULL,
  subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  syllabus TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_curriculum_branch ON curriculum(branch_id);

-- RLS: sections
ALTER TABLE sections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read sections in their school"
  ON sections FOR SELECT
  USING (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    OR branch_id IN (SELECT b.id FROM branches b JOIN profiles p ON p.school_id = b.school_id WHERE p.id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'super_admin')
  );

CREATE POLICY "Academic roles can manage sections"
  ON sections FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('super_admin', 'academic_admin'))
  );

-- RLS: classes, subjects, curriculum (similar pattern)
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read classes in their school"
  ON classes FOR SELECT
  USING (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    OR branch_id IN (SELECT b.id FROM branches b JOIN profiles p ON p.school_id = b.school_id WHERE p.id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'super_admin')
  );

CREATE POLICY "Academic roles can manage classes"
  ON classes FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('super_admin', 'academic_admin'))
  );

CREATE POLICY "Users can read subjects in their school"
  ON subjects FOR SELECT
  USING (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    OR branch_id IN (SELECT b.id FROM branches b JOIN profiles p ON p.school_id = b.school_id WHERE p.id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'super_admin')
  );

CREATE POLICY "Academic roles can manage subjects"
  ON subjects FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('super_admin', 'academic_admin'))
  );

CREATE POLICY "Users can read curriculum in their school"
  ON curriculum FOR SELECT
  USING (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    OR branch_id IN (SELECT b.id FROM branches b JOIN profiles p ON p.school_id = b.school_id WHERE p.id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'super_admin')
  );

CREATE POLICY "Academic roles can manage curriculum"
  ON curriculum FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('super_admin', 'academic_admin'))
  );

-- RLS: guardians
ALTER TABLE guardians ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read guardians in their school"
  ON guardians FOR SELECT
  USING (
    school_id IN (SELECT school_id FROM profiles WHERE id = auth.uid())
    OR school_id IN (SELECT school_id FROM profiles WHERE id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'super_admin')
    OR auth_user_id = auth.uid()
  );

CREATE POLICY "Academic roles can manage guardians"
  ON guardians FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('super_admin', 'academic_admin'))
  );

-- RLS: students
ALTER TABLE students ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read students in their school"
  ON students FOR SELECT
  USING (
    school_id IN (SELECT school_id FROM profiles WHERE id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'super_admin')
    OR auth_user_id = auth.uid()
    OR id IN (SELECT gs.student_id FROM guardian_students gs JOIN guardians g ON g.id = gs.guardian_id WHERE g.auth_user_id = auth.uid())
  );

CREATE POLICY "Academic roles can manage students"
  ON students FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('super_admin', 'academic_admin'))
  );

-- RLS: guardian_students
ALTER TABLE guardian_students ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read guardian_students in their school"
  ON guardian_students FOR SELECT
  USING (
    guardian_id IN (SELECT id FROM guardians WHERE school_id IN (SELECT school_id FROM profiles WHERE id = auth.uid()))
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'super_admin')
  );

CREATE POLICY "Academic roles can manage guardian_students"
  ON guardian_students FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('super_admin', 'academic_admin'))
  );

-- RLS: admission_applications
ALTER TABLE admission_applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read admissions in their school"
  ON admission_applications FOR SELECT
  USING (
    school_id IN (SELECT school_id FROM profiles WHERE id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'super_admin')
  );

CREATE POLICY "Academic roles can manage admissions"
  ON admission_applications FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('super_admin', 'academic_admin'))
  );

-- Allow anonymous insert for public admissions form
CREATE POLICY "Anyone can submit admission application"
  ON admission_applications FOR INSERT
  WITH CHECK (true);

-- RLS: timetable_slots
ALTER TABLE timetable_slots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read timetable in their school"
  ON timetable_slots FOR SELECT
  USING (
    class_id IN (SELECT c.id FROM classes c JOIN branches b ON b.id = c.branch_id WHERE b.school_id IN (SELECT school_id FROM profiles WHERE id = auth.uid()))
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'super_admin')
  );

CREATE POLICY "Academic roles can manage timetable"
  ON timetable_slots FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('super_admin', 'academic_admin'))
  );
